### ISSUE TITLE
"/Users/js already exists. Do you want to overwrite it?"

### ISSUE THREAD

**Issue by jsandlund** [iron-meteor/iron-cli#232] opened 2016-02-02 16:35 UTC
I keep running into errors when running generate commands. I'm first prompted with a cryptic this file already exists message (can't find this file anywhere):

`/Users/js already exists. Do you want to overwrite it? [yn]:`

If I say yes, it throws an EAccess error. 

![image](https://cloud.githubusercontent.com/assets/4348388/12756237/b0e75020-c987-11e5-86ee-5476703769b9.png)

If I sudo my way through this permission error it appears to work but no markup is generated. I've tried uninstalling & re-installing to no avail. Thoughts on what's happening?

**Comment by chrisbutler** [comment] 2016-02-02 21:57
@jsandlund that's bizarre. the paths it's using don't make sense.

can you try creating a project without dashes in the name, and see if it still behaves the same way?

**Comment by jsandlund** [comment] 2016-02-03 04:48
Strange. It's trying to write to the same unknown path `/Users/js/` when I run `iron create`. 

![image](https://cloud.githubusercontent.com/assets/4348388/12773239/60a2925c-c9ee-11e5-927b-625e6400e1c4.png)

**Comment by jsandlund** [comment] 2016-02-04 03:18
Super strange. Played around a bit more. Appears to only run into an issue when creating the .js file. Only potential cause I can think off: maybe something to do with my username being '**js**andlund', which creates a side effect when something is being parsed. 

![image](https://cloud.githubusercontent.com/assets/4348388/12804787/f72a460e-caaa-11e5-86c5-144a9ee5a27e.png)

**Comment by chrisbutler** [comment] 2016-02-04 16:54
that is quite possible, i'll try to test out some stuff when i get a chance

**Comment by jsandlund** [comment] 2016-02-05 15:43
Yep, confident my alias is the root cause. Changed it last night to not be prefixed with `js`, same environment, and everything worked fine. I poked around the iron-cli's `lib` files to see if I could find the culprit but no luck. (Apologies, my node.js is super weak.)

**Comment by chrisbutler** [comment] 2016-02-05 15:53
@jsandlund in that case, i'm pretty sure the issue is with `rewriteSourcePathForEngine` or `rewriteDestinationPathForEngine' and the regex-based replacing that is happening in https://github.com/iron-meteor/iron-cli/blob/master/lib/tools/file_system.js

**Comment by jsec** [comment] 2016-03-16 21:11
Can confirm the alias hypothesis as well. `iron create appname` fails with the same error for me, with username "jsec"

**Comment by chrisbutler** [comment] 2017-01-12 22:27
@jsandlund @jsec this is fixed in 1.8.0 !

**Closed by chrisbutler** 2017-01-12 22:27 UTC
Labels: bug
